memgrind: memgrind.o mymallo

memgrind.o: memgrind.c mymalloc.h
	gcc -c memgrind.c -o memgrind

mymalloc.o: mymalloc.c mymalloc.h
	gcc -c mymalloc.c -o mymalloc

clean: 
	rm -f memgrind *.o
